/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import webbanking.Cuenta;
import webbanking.BaseDatos;
import webbanking.db.Consultas;
import webbanking.operaciones.Deposito;

/**
 *
 * @author User
 */
public class GUIDeposito extends javax.swing.JFrame {
    
    private final Cuenta cuenta;
    
    public GUIDeposito(Cuenta cuenta) {
        this.cuenta = cuenta;
        
        initComponents(); // Inicializa los elementos gráficos
        setTitle("Depósito"); // Configura el título de la ventana
        setSize(400, 400); // Establece el tamaño de la ventana
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Monto");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nº ID");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField2.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Introduzca el ID");
        } else {
            final String id = jTextField2.getText();
            
            new Thread(() -> {
            try {
                // Intentar convertir el ID a un número
                long ID = Long.parseLong(id);

                Cuenta cuentaid = Consultas.obtenerCuenta(ID) ;

                if (cuentaid != null) {
                    JOptionPane.showMessageDialog(rootPane, "Cuenta encontrada: " + cuentaid.gettitular());
                    if (jTextField1.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(rootPane, "Introduzca el monto");
                    } else {
                        final String monto = jTextField1.getText();
                        if(Integer.parseInt(monto ) <= 0 ){
                            JOptionPane.showMessageDialog(rootPane, "El depósito debe ser mayor a 0");
                        }else if(Double.parseDouble(monto ) > cuenta.getSaldo()){
                            JOptionPane.showMessageDialog(rootPane, "El depósito no debe ser mayor que el su saldo");
                        }else{
                            try {
                                // Intentar convertir el monto a un valor double
                                double montoDouble = Double.parseDouble(monto);

                                Deposito dep = new Deposito(montoDouble);
                                dep.setCuentaDestino(cuentaid); // cuenta destino
                                Thread.sleep(1000);
                                dep.depositar();
                                String fecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new Date());
                                String mensaje = "Operación realizada con éxito\n"
                                        + "Fecha: " + fecha + "\n"
                                        + "Cuenta: " + cuentaid.getIDcuenta() + "\n"
                                        + "Descripción: Depósito\n"
                                        + "Monto: " + monto;

                                JOptionPane.showMessageDialog(this, mensaje);
                                if(cuentaid.getIDcuenta() == cuenta.getIDcuenta()){
                                    cuenta.setSaldo(cuentaid.getSaldo());
                                }
                                GUIMenuPrincipal mp = new GUIMenuPrincipal(cuenta);
                                mp.setVisible(true);
                                //dispose();
                            } catch (NumberFormatException e) {
                                JOptionPane.showMessageDialog(rootPane, "El monto debe ser un número válido");
                            }
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No se encontró una cuenta con el ID especificado.");
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "El ID debe ser un número válido.");
            } catch (InterruptedException e) {
                System.err.println("El hilo fue interrumpido.");
                Thread.currentThread().interrupt();
            }
        }).start();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        Cuenta cuenta= new Cuenta("","", "",0,0, "",0,0);
        
        GUIDeposito dep=new GUIDeposito(cuenta);
        dep.setVisible(true);
        
        //java.awt.EventQueue.invokeLater(new Runnable() {
        //    @Override
        //    public void run() {
        //        new GUIDeposito(cuenta,baseDatos).setVisible(true);
        //    }
        //});
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
