/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import webbanking.BaseDatos;
import webbanking.Cuenta;

/**
 *
 * @author User
 */
public class GUIPagoServicios extends javax.swing.JFrame {
    
    Cuenta cuenta;
    BaseDatos baseDatos;
    GUIMenuPrincipal menuPrincipal;
    
    public GUIPagoServicios(Cuenta cuenta, BaseDatos baseDatos, GUIMenuPrincipal menuPrincipal) {
        this.cuenta = cuenta;
        this.baseDatos = baseDatos;
        this.menuPrincipal = menuPrincipal;
        initComponents();
        setTitle("Pago Servcios"); // Configura el título de la ventana
        setSize(400, 400); // Establece el tamaño de la ventana
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Luz", "Agua", "Internet", "Teléfono" }));
        jComboBox1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jComboBox1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione un servicio");

        jLabel2.setText("Monto a pagar");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 115, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(94, 94, 94)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jComboBox1.getAccessibleContext().setAccessibleName("");
        jComboBox1.getAccessibleContext().setAccessibleDescription("");
        jComboBox1.getAccessibleContext().setAccessibleParent(jComboBox1);
        jButton1.getAccessibleContext().setAccessibleName("J");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBox1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1CaretPositionChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Introduzca el monto");
        } else {
            try {
                double monto = Double.parseDouble(jTextField1.getText());
                
                new Thread(() -> {
                    try {
                        // Mostrar la ventana de verificación del PIN
                        GUIPinTransaccion pinDialog = new GUIPinTransaccion(this, "Verificar PIN Transaccion", cuenta.getPinTransaccion());
                        pinDialog.setVisible(true);

                        if (pinDialog.validarcontraseña()) {
                            String servicio = (String) jComboBox1.getSelectedItem();
                            Thread.sleep(5000);
                            realizarPago(monto, servicio);                
                            if (menuPrincipal != null) {
                                menuPrincipal.actualizarSaldo(cuenta.getSaldo());
                            }
                        
                        } else {
                            JOptionPane.showMessageDialog(this, "PIN incorrecto. Operación cancelada.");
                        }
                    }catch(Exception e){
                        System.err.println("El hilo fue interrumpido.");                     
                    }
                }).start();
                
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "El monto debe ser un número válido");
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    private void realizarPago(double monto,String servicio) {
        try {
            long ID = (long) cuenta.getIDcuenta();
            baseDatos.PagoServicios(ID, monto);
            
            String fecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new Date());
            String mensaje = "Operación realizada con éxito\n" +
                             "Fecha: " + fecha + "\n" +
                             "Cuenta: " + cuenta.getIDcuenta() + "\n" +
                             "Descripción: Pago de servicio "+servicio +
                             "\nMonto: " + monto;
            JOptionPane.showMessageDialog(this, mensaje);
            //dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al realizar el pago: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        BaseDatos baseDatos = new BaseDatos();
        Cuenta cuenta= new Cuenta("","", "",0,0, "",0,0);
        GUIMenuPrincipal menuPrincipal = new GUIMenuPrincipal(cuenta,baseDatos);
        GUIPagoServicios dep=new GUIPagoServicios(cuenta, baseDatos,menuPrincipal);
        dep.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
