/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.OptionPaneUI;
import variablesGlobales.MensajesError;
import variablesGlobales.MensajesExito;
import webbanking.Cuenta;
import webbanking.operaciones.Transferencia;

/**
 *
 * @author sotelo
 */
public class GUITransaccionFormulario extends javax.swing.JFrame {
    JLabel error = new JLabel();
    private Cuenta cuenta;

    /**
     * Creates new form GUITransaccionFormulario
     */
    public GUITransaccionFormulario(Cuenta cuenta) {
        this.setLocationRelativeTo(null);//centra la ventana en la pantalla
        this.cuenta = cuenta;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        monto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cuentaDestino = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        cuentaOrigen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario transaccion");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Cuenta origen:");

        jLabel2.setText("Monto a transferir:");

        monto.setForeground(new java.awt.Color(204, 204, 204));
        monto.setToolTipText("Ingresa el monto");
        monto.setName("monto"); // NOI18N
        monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoActionPerformed(evt);
            }
        });

        jLabel5.setText("No. Cuenta destino");

        cuentaDestino.setForeground(new java.awt.Color(204, 204, 204));
        cuentaDestino.setToolTipText("Ingresa numero de cuenta");
        cuentaDestino.setName("cuentaDestino"); // NOI18N
        cuentaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaDestinoActionPerformed(evt);
            }
        });

        Aceptar.setText("Aceptar");
        Aceptar.setName("realizarTransaccion"); // NOI18N
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        cuentaOrigen.setEditable(false);
        cuentaOrigen.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cuentaOrigen.setText("ID cuenta: "+ Long.toString(cuenta.getIDcuenta()));
        cuentaOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaOrigenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Aceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(monto, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Cancelar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void montoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_montoActionPerformed

    private void cuentaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuentaDestinoActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        
        try {
            String cuentaDestinoText = cuentaDestino.getText().trim();
            String montoText = monto.getText().trim();

            if (cuentaDestinoText.isEmpty() || montoText.isEmpty()) {
                JOptionPane.showMessageDialog(this, MensajesError.ERROR_FORMULARIO, "Error", JOptionPane.ERROR_MESSAGE);
            } else if (!esNumeroValido(cuentaDestinoText) || !esNumeroValido(montoText)) {
                JOptionPane.showMessageDialog(this, MensajesError.ERROR_CAMPO_NUMERICO, "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                long cuentaDestinoID = Long.parseLong(cuentaDestinoText);
                double montoTransferencia = Double.parseDouble(montoText);

                Transferencia t = new Transferencia(cuentaDestinoID, montoTransferencia, cuenta);
                Transferencia response = t.Transferir();

                if (response.getMensaje() == null || response.getMensaje().isEmpty()) {
                    dispose();
                    JOptionPane.showMessageDialog(this, MensajesExito.EXITO_ACTUALIZACION);
                } else {
                    JOptionPane.showMessageDialog(this, response.getMensaje());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, MensajesError.ERROR_INESPERADO, "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }



    }//GEN-LAST:event_AceptarActionPerformed

    private boolean esNumeroValido(String input) {
        try {
            Double.parseDouble(input); // También válido para enteros
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    private void cuentaOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaOrigenActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cuentaOrigenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITransaccionFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITransaccionFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITransaccionFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITransaccionFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Cuenta cuenta=new Cuenta("","", "",0,0, "",0,0);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITransaccionFormulario(cuenta).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField cuentaDestino;
    private javax.swing.JTextField cuentaOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField monto;
    // End of variables declaration//GEN-END:variables
}
